name: .NET 项目构建与发布

on:
  push:
    branches:
      # - 'main' # 建议将监听分支改为 'main' 或 'master'
      # - 'master'
      # - 'release/**' # 如果有专门的发布分支
       - '**' # 如果您确实需要在所有分支都尝试运行，请理解可能导致标签冲突的概率增加

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 显式授予对仓库内容的写入权限，用于创建标签和 Release

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # GitVersion 需要完整的 Git 历史来计算版本

      - name: 设置 .NET 环境
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 安装 GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0 # 检查最新版本
        with:
          versionSpec: '5.x' # 指定 GitVersion 版本

      - name: 获取 GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.11.0 # 检查最新版本
        with:
          # --- 解决 GitVersion 警告：'target-path' -> 'targetPath' ---
          targetPath: '.'

      - name: 显示版本号
        run: |
          echo "语义化版本号: ${{ steps.gitversion.outputs.semVer }}"
          echo "完整版本号: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: 恢复依赖项
        run: dotnet restore

      # 构建 Release 版本 (移除 --output)
      - name: 构建 Release 版本
        # --- 解决 dotnet build --output 警告：移除 --output ---
        run: dotnet build --configuration Release --no-restore

      # 发布 Release 版本
      - name: 发布 Release 版本
        run: dotnet publish --configuration Release --no-restore --output ./publish/Release

      # 构建 Debug 版本 (移除 --output)
      - name: 构建 Debug 版本
        # --- 解决 dotnet build --output 警告：移除 --output ---
        run: dotnet build --configuration Debug --no-restore

      # 发布 Debug 版本
      - name: 发布 Debug 版本
        run: dotnet publish --configuration Debug --no-restore --output ./publish/Debug

      # --- 新增步骤：打包发布文件 ---
      - name: 打包发布文件
        run: |
          # 假设您的项目名称为 'MyPlugin' 或类似
          # 您可以根据实际项目名称调整此处
          PLUGIN_NAME="cs2-prophunt" # <<<<<<<<<<<<<<<< 请在这里替换为您的插件或项目名称

          # 打包 Release 版本
          zip -r "${PLUGIN_NAME}-Release-v${{ steps.gitversion.outputs.semVer }}.zip" ./publish/Release/
          echo "打包文件: ${PLUGIN_NAME}-Release-v${{ steps.gitversion.outputs.semVer }}.zip 已创建"

          # 打包 Debug 版本
          zip -r "${PLUGIN_NAME}-Debug-v${{ steps.gitversion.outputs.semVer }}.zip" ./publish/Debug/
          echo "打包文件: ${PLUGIN_NAME}-Debug-v${{ steps.gitversion.outputs.semVer }}.zip 已创建"

      - name: 生成并推送发布标签
        id: create_tag
        run: |
          TAG_NAME="v${{ steps.gitversion.outputs.semVer }}"
          echo "即将生成的标签名称: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV # 将标签名存入环境变量供后续步骤使用

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 检查标签是否已经存在于远程仓库
          if git ls-remote origin refs/tags/$TAG_NAME | grep -q $TAG_NAME; then
            echo "警告：标签 $TAG_NAME 已存在于远程仓库。跳过标签创建和推送。"
          else
            echo "正在创建并推送新标签: $TAG_NAME"
            git tag $TAG_NAME
            git push origin $TAG_NAME
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }} # 使用 GitVersion 生成的标签名
          generate_release_notes: true # 自动生成发布说明
          files: |
            # --- 上传打包好的 .zip 文件 ---
            ./*.zip # 匹配当前目录下所有 .zip 文件
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
